/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.5).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.ContingencyTable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-03-04T11:51:52.090Z[GMT]")
@Api(value = "contingencyTableNames", description = "the contingencyTableNames API")
public interface ContingencyTableNamesApi {

    @ApiOperation(value = "Uses drug and outcome names in RxNorm and SNOMEDCT respectively to search AEOLUS and produce the corresponding contingency table.", nickname = "contingencyTableNames", notes = "Makes drug/outcome coded query and returns two by two contingency table.", response = Object.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response", response = Object.class, responseContainer = "List") })
    @RequestMapping(value = "/contingencyTableNames",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<ContingencyTable>> contingencyTableNames(@NotNull @ApiParam(value = "RxNorm-standard drug name for search", required = true) @Valid @RequestParam(value = "drugName", required = true) String drugName, @NotNull @ApiParam(value = "SNOMEDCT-standard outcome name for search", required = true) @Valid @RequestParam(value = "outcomeName", required = true) String outcomeName);

}
